kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:{{ include "aliyun-ccm.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ include "aliyun-ccm.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "aliyun-ccm.serviceAccountName" . }}
  namespace: {{ include "aliyun-ccm.namespace" . }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:shared-informers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ include "aliyun-ccm.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: shared-informers
  namespace: {{ include "aliyun-ccm.namespace" . }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:cloud-node-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ include "aliyun-ccm.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: cloud-node-controller
  namespace: {{ include "aliyun-ccm.namespace" . }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:pvl-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ include "aliyun-ccm.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: pvl-controller
  namespace: {{ include "aliyun-ccm.namespace" . }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:route-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ include "aliyun-ccm.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: route-controller
  namespace: {{ include "aliyun-ccm.namespace" . }}
