apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aliyun-ccm.secretName" . }}
  namespace: {{ include "aliyun-ccm.namespace" . }}
data:
  cloud-config.conf: |-
    {
        "Global": {
            "AccessKeyID": "{{ .Values.permission.accessKeyID }}",              
            "AccessKeySecret": "{{ .Values.permission.accessKeySecret }}" 
        }
    }